name: Package and create artifact

on:
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths:
      - '**.lua'
      - '**.toc'
      - '.pkgmeta'

jobs:
  alpha:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v6

      - name: Package
        uses: BigWigsMods/packager@v2
        with:
          args: -z -d
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}

      - name: Get short commit sha
        id: sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: Molinari-${{ steps.sha.outputs.sha_short }}
          path: .release/
          include-hidden-files: true
