name: Upload localization strings to CurseForge

on:
  push:
    branches:
      - master
    tags-ignore:
      - '**'
    paths:
      - '**.toc'
      - '**.lua'
      - '**.xml'
      - '.github/workflows/translations.yml'
      - '!data/'
      - '!locale/'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v6

      - name: Upload localizations
        uses: p3lim/curseforge-localizations@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          HANDLE_MISSING: DeletePhrase
